# Rust code formatting configuration
# See https://rust-lang.github.io/rustfmt for all options

# Edition
edition = "2021"

# Maximum line width
max_width = 100

# Indentation
tab_spaces = 4
hard_tabs = false

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true

# Formatting style
fn_single_line = false
where_single_line = false
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
comment_width = 80

# Trailing elements
trailing_comma = "Vertical"
trailing_semicolon = true

# Match blocks
match_block_trailing_comma = true
match_arm_blocks = true

# Use field init shorthand
use_field_init_shorthand = true

# Use try shorthand
use_try_shorthand = true

# Blank lines
blank_lines_upper_bound = 2
blank_lines_lower_bound = 0

# Newline style
newline_style = "Auto"

# Control flow
control_brace_style = "AlwaysSameLine"
brace_style = "SameLineWhere"
indent_style = "Block"

# Misc
remove_nested_parens = true
reorder_impl_items = true
overflow_delimited_expr = true

