# Clippy configuration
# See https://doc.rust-lang.org/clippy/lint_configuration.html

# Maximum cognitive complexity before clippy warns
cognitive-complexity-threshold = 30

# Maximum lines in a function before clippy warns
too-many-lines-threshold = 150

# Maximum number of arguments before clippy warns
too-many-arguments-threshold = 8

# Maximum number of single char bindings in scope
single-char-binding-names-threshold = 4

# Type complexity limit
type-complexity-threshold = 500

# Avoid breaking exported API
avoid-breaking-exported-api = true

